#---------------------------------------------------------------------------------
.SUFFIXES:
# Delete a half-written target when linking fails, so the next make does not hand a broken
# ELF to elf2nro (which would report "expected AArch64").
.DELETE_ON_ERROR:
#---------------------------------------------------------------------------------

ifeq ($(strip $(DEVKITPRO)),)
$(error "Please set DEVKITPRO in your environment. export DEVKITPRO=<path to>/devkitpro")
endif

TOPDIR ?= $(CURDIR)
include $(DEVKITPRO)/libnx/switch_rules

#---------------------------------------------------------------------------------
TARGET		:=	acnh-manager
BUILD		:=	build
SOURCES		:=	source source/manifest source/install source/env source/ui source/i18n source/util source/net source/payload
# The files in data/ are turned into .rodata symbols by bin2s (embedded release manifest
# and payload; see tools/import-agent-release.py).
DATA		:=	data
INCLUDES	:=	source

APP_TITLE	:=	ACNH-Manager
APP_AUTHOR	:=	leolovenet
APP_VERSION	:=	0.1.0

# The build stamp comes from tools/build.sh (UTC time + commit); a manual make gets a stub.
BUILD_STAMP	?=	manual

# NACP icon (shown by hbmenu/the album); generated by tools/make-icons.py.
ICON		:=	assets/icon.jpg

#---------------------------------------------------------------------------------
ARCH	:=	-march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE

CFLAGS	:=	-g -Wall -Wextra -O2 -ffunction-sections \
			$(ARCH) $(DEFINES)

# Aggregate initializers in libnx's headers trip -Wextra's missing-field-initializers; that
# is not our code, so keep it quiet to stay at zero warnings.
CFLAGS	+=	-Wno-missing-field-initializers

CFLAGS	+=	$(INCLUDE) -D__SWITCH__
CFLAGS	+=	-DACNH_BUILD_STAMP="\"$(BUILD_STAMP)\""
# FreeType's headers live under portlibs/freetype2 (must be added before CXXFLAGS).
CFLAGS	+=	-I$(PORTLIBS)/include/freetype2

CXXFLAGS	:= $(CFLAGS) -fno-rtti -fno-exceptions -std=gnu++17

ASFLAGS	:=	-g $(ARCH)
LDFLAGS	=	-specs=$(DEVKITPRO)/libnx/switch.specs -g $(ARCH) -Wl,-Map,$(notdir $*.map)

# The static FreeType brings harfbuzz auto-hinting, PNG and bzip2 along; all four link libs
# have to be listed explicitly.
LIBS	:= -lfreetype -lharfbuzz -lpng -lbz2 -lcurl -lmbedtls -lmbedx509 -lmbedcrypto -lz -lnx

LIBDIRS	:= $(PORTLIBS) $(LIBNX)

#---------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))
#---------------------------------------------------------------------------------

export OUTPUT	:=	$(CURDIR)/$(TARGET)
export TOPDIR	:=	$(CURDIR)

export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
			$(foreach dir,$(DATA),$(CURDIR)/$(dir))

export DEPSDIR	:=	$(CURDIR)/$(BUILD)

CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
SFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))
BINFILES	:=	$(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

ifeq ($(strip $(CPPFILES)),)
	export LD	:=	$(CC)
else
	export LD	:=	$(CXX)
endif

export OFILES_BIN	:=	$(addsuffix .o,$(BINFILES))
export OFILES_SRC	:=	$(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(SFILES:.s=.o)
export OFILES 	:=	$(OFILES_BIN) $(OFILES_SRC)
export HFILES_BIN	:=	$(addsuffix .h,$(subst .,_,$(BINFILES)))

export INCLUDE	:=	$(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
			$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
			-I$(CURDIR)/$(BUILD)

export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib)

ifeq ($(strip $(ICON)),)
	icons := $(wildcard *.jpg)
	ifneq (,$(findstring $(TARGET).jpg,$(icons)))
		export APP_ICON := $(TOPDIR)/$(TARGET).jpg
	else
		ifneq (,$(findstring icon.jpg,$(icons)))
			export APP_ICON := $(TOPDIR)/icon.jpg
		endif
	endif
else
	export APP_ICON := $(TOPDIR)/$(ICON)
endif

ifeq ($(strip $(NO_ICON)),)
	export NROFLAGS += --icon=$(APP_ICON)
endif

ifeq ($(strip $(NO_NACP)),)
	export NROFLAGS += --nacp=$(CURDIR)/$(TARGET).nacp
endif

.PHONY: $(BUILD) clean all

#---------------------------------------------------------------------------------
all: $(BUILD)

$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile

clean:
	@echo clean ...
	@rm -fr $(BUILD) $(TARGET).nro $(TARGET).nacp $(TARGET).elf $(TARGET).lst

#---------------------------------------------------------------------------------
else
.PHONY:	all

DEPENDS	:=	$(OFILES:.o=.d)

# Force a rebuild when the stamp changes: touch only when the content differs, so an
# unchanged stamp does not rebuild the world every time.
STAMP_DEP	:=	$(BUILD)/build-stamp

all	:	$(OUTPUT).nro

$(OUTPUT).nro	:	$(OUTPUT).elf $(OUTPUT).nacp

$(OUTPUT).elf	:	$(OFILES)

$(OFILES): $(STAMP_DEP)

$(STAMP_DEP): FORCE
	@mkdir -p $(dir $@)
	@echo '$(BUILD_STAMP)' | cmp -s - $@ 2>/dev/null || echo '$(BUILD_STAMP)' > $@

.PHONY: FORCE
FORCE:

%.o: %.cpp
	@echo $(notdir $<)
	@$(CXX) -MMD -MP -MF $(DEPSDIR)/$*.d $(CXXFLAGS) -c $< -o $@

%.o: %.c
	@echo $(notdir $<)
	@$(CC) -MMD -MP -MF $(DEPSDIR)/$*.d $(CFLAGS) -c $< -o $@

%.o: %.s
	@echo $(notdir $<)
	@$(CC) -MMD -MP -MF $(DEPSDIR)/$*.d -x assembler-with-cpp $(ASFLAGS) -c $< -o $@

# Binary data in data/: bin2s generates <name>.o plus a <name>.h header (symbol name =
# the file name with dots replaced by underscores).  The header lands in $(BUILD), which
# is on the include path, so sources can just #include "subsdk9_bin.h".
# The pattern rule must be "%.bin.o: %.bin" (the devkitPro convention): every file in
# DATA has to carry the .bin suffix.
define bin2o
	bin2s -a 4 -H `(echo $(<F) | tr . _)`.h $< | { cat; echo; } | $(AS) -o $@
endef

%.bin.o: %.bin
	@echo $(notdir $<)
	@$(bin2o)

# The generated headers are a by-product of the rule above; make the dependency explicit so
# a parallel build (-j) can never compile a source before its header exists.
embedded.o: $(OFILES_BIN)

-include $(DEPENDS)

endif
#---------------------------------------------------------------------------------
