#include "payload/embedded.hpp"

/* Generated by devkitPro's bin2s (dots in file names become underscores):
   data/subsdk9.bin            -> subsdk9_bin / subsdk9_bin_size
   data/main_npdm.bin          -> main_npdm_bin / main_npdm_bin_size
   data/acnh_agent_version.bin -> acnh_agent_version_bin / acnh_agent_version_bin_size
   data/manifest.bin           -> manifest_bin / manifest_bin_size
   data/agent_pubkey.bin       -> agent_pubkey_bin / agent_pubkey_bin_size
   These headers are generated into the build/ directory (the build passes -I for it). */
#include "acnh_agent_version_bin.h"
#include "agent_pubkey_bin.h"
#include "main_npdm_bin.h"
#include "manifest_bin.h"
#include "subsdk9_bin.h"

#include "i18n/strings.hpp"

namespace acnh_manager::payload {
namespace {

struct Entry {
    const char *name; /* must match files[].source in the manifest */
    const u8 *data;
    std::size_t size;
};

constexpr Entry kEntries[] = {
    {"subsdk9", subsdk9_bin, subsdk9_bin_size},
    {"main.npdm", main_npdm_bin, main_npdm_bin_size},
    {"acnh-agent.version", acnh_agent_version_bin, acnh_agent_version_bin_size},
};

constexpr std::size_t kEntryCount = sizeof(kEntries) / sizeof(kEntries[0]);

}  // namespace

std::string_view EmbeddedManifestJson() {
    return std::string_view(reinterpret_cast<const char *>(manifest_bin), manifest_bin_size);
}

std::string_view EmbeddedAgentPublicKeyPem() {
    return std::string_view(reinterpret_cast<const char *>(agent_pubkey_bin),
                            agent_pubkey_bin_size);
}

bool EmbeddedAvailable() {
    if (manifest_bin_size == 0) {
        return false;
    }
    for (const Entry &entry : kEntries) {
        if (entry.size == 0) {
            return false;
        }
    }
    return true;
}

bool EmbeddedPayloadSource::Read(const std::string &name, std::vector<u8> *out,
                                 std::string *error) {
    for (std::size_t i = 0; i < kEntryCount; ++i) {
        if (name != kEntries[i].name) {
            continue;
        }
        if (out != nullptr) {
            out->assign(kEntries[i].data, kEntries[i].data + kEntries[i].size);
        }
        return true;
    }
    if (error != nullptr) {
        *error = i18n::Format(i18n::StringId::PayloadNotEmbedded, name.c_str());
    }
    return false;
}

}  // namespace acnh_manager::payload
