#!/usr/bin/env python3
"""Build a "dev manifest" plus payload directory from acnh-agent build output (for on-device dry runs).

It does three things:
It does three things:
  1. read acnh-agent's dist/version.json, dist/acnh-agent.nso and the derived NPDM;
  2. write dev-manifest.json following the current contract (**keeping the real buildFlags/dirty**);

Output goes to the ignored build/scratch/dev-payload/, which tools/deploy-nro.py then pushes to the SD:
    /switch/ACNH-Manager/dev-manifest.json
    /switch/ACNH-Manager/payload/{subsdk9,main.npdm,acnh-agent.version}

Note: a development build carries the DEV/RPC bits and the manifest check refuses it by design;
that gate is deliberate.  To dry-run the flow, allow dev manifests on the app's settings page.

Usage:
    python3 tools/make-dev-manifest.py
    python3 tools/make-dev-manifest.py --nso ../acnh-agent/dist/acnh-agent.nso \
        --npdm ../acnh-agent/dist/acnh-3.0.3-frame-hook-self/main.npdm \
        --version-json ../acnh-agent/dist/version.json --out build/scratch/dev-payload
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import shutil
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
WORKSPACE = REPO_ROOT.parent.parent
AGENT = WORKSPACE / "src" / "acnh-agent"

DEFAULT_NSO = AGENT / "dist" / "acnh-agent.nso"
DEFAULT_NPDM = AGENT / "dist" / "acnh-3.0.3-frame-hook-self" / "main.npdm"
DEFAULT_VERSION_JSON = AGENT / "dist" / "version.json"
DEFAULT_OUT = REPO_ROOT / "build" / "scratch" / "dev-payload"

EXEFS = "atmosphere/contents/01006F8002326000/exefs"
CONTENT_ID = "E10617820DB06889E1638499478DA0DE"
BUILD_ID = "FF1D1C05670DB6021C85B624A710B963"
TITLE_VERSION = 2228224


def sha256_of(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nso", type=pathlib.Path, default=DEFAULT_NSO)
    parser.add_argument("--npdm", type=pathlib.Path, default=DEFAULT_NPDM)
    parser.add_argument("--version-json", type=pathlib.Path, default=DEFAULT_VERSION_JSON)
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    for path in (args.nso, args.npdm, args.version_json):
        if not path.is_file():
            print(f"error: missing input {path}", file=sys.stderr)
            return 1

    version = json.loads(args.version_json.read_text())
    nso_sha = sha256_of(args.nso)
    npdm_sha = sha256_of(args.npdm)
    version_sidecar = args.version_json.read_bytes()

    out_payload = args.out / "payload"
    out_payload.mkdir(parents=True, exist_ok=True)
    files = [
        ("subsdk9", args.nso, f"{EXEFS}/subsdk9", nso_sha, "game"),
        ("main.npdm", args.npdm, f"{EXEFS}/main.npdm", npdm_sha, "game"),
    ]
    # The sidecar goes into the payload directory; the manifest simply uses its hash.
    sidecar = out_payload / "acnh-agent.version"
    sidecar.write_bytes(version_sidecar)
    files.append(("acnh-agent.version", sidecar, f"{EXEFS}/acnh-agent.version",
                  hashlib.sha256(version_sidecar).hexdigest(), "none"))
    for name, source, _target, _sha, _restart in files:
        if source != sidecar:
            shutil.copyfile(source, out_payload / name)

    manifest = {
        "schema": 1,
        "channel": "dev",
        "generated": "",
        "app": {"minVersion": "0.1.0"},
        "agent": {
            "version": version.get("agentVersion", "unknown"),
            "commit": version.get("commit", "unknown"),
            "dirty": bool(version.get("dirty", True)),
            "buildFlags": int(version.get("buildFlags", 0)),
        },
        "baseUrl": (f"https://gitee.com/acnh-game/acnh-manager/raw/main/"
                    f"packaging/agent/{version.get('agentVersion', 'dev')}/"),
        "changelog": "dev payload generated by tools/make-dev-manifest.py",
        "games": [
            {
                "profile": "v3_0_3",
                "titleId": "01006F8002326000",
                "version": TITLE_VERSION,
                "displayVersion": "3.0.3",
                "contentId": CONTENT_ID,
                "buildId": BUILD_ID,
                "files": [
                    {"name": name, "source": name, "target": target, "size": size, "sha256": sha,
                     "restart": restart}
                    for (name, _src, target, sha, restart), size in zip(
                        files,
                        [args.nso.stat().st_size, args.npdm.stat().st_size, len(version_sidecar)],
                    )
                ],
            }
        ],
    }
    manifest_path = args.out / "dev-manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"agent {manifest['agent']['version']} commit={manifest['agent']['commit']} "
          f"dirty={manifest['agent']['dirty']} buildFlags={manifest['agent']['buildFlags']}")
    print(f"wrote {manifest_path}")
    for name, _source, target, sha, _restart in files:
        print(f"  {out_payload / name}  ->  {target}  sha256={sha[:16]}…")
    if manifest["agent"]["buildFlags"] != 2 or manifest["agent"]["dirty"]:
        print("note: this is a development build and the release gate will refuse it; "
              "allow dev manifests in the app settings for an on-device dry run.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
