#!/usr/bin/env python3
"""从 acnh-agent 的构建产物生成"开发用清单"与 payload 目录(M2 真机干跑用)。

它做三件事:
  1. 读 acnh-agent 的 dist/version.json 与 dist/acnh-agent.nso,以及派生 NPDM;
  2. 按当前清单契约生成 dev-manifest.json(**保留真实的 buildFlags/dirty**,不做任何美化);
  3. 把 payload 文件复制到输出目录,文件名与清单里的 source 对齐。

产物默认写到本仓库已忽略的 build/scratch/dev-payload/,再由 tools/deploy-nro.py 推到 SD:
    /switch/ACNH-Manager/dev-manifest.json
    /switch/ACNH-Manager/payload/{subsdk9,main.npdm,acnh-agent.version}

注意:开发构建的 buildFlags 含 DEV/RPC 位,清单校验默认会拒绝它——这是有意设计的
发布门控。要在 M4 之前干跑流程,请在 App 设置页显式打开"允许开发清单"。

用法:
    python3 tools/make-dev-manifest.py
    python3 tools/make-dev-manifest.py --nso ../acnh-agent/dist/acnh-agent.nso \
        --npdm ../acnh-agent/dist/acnh-3.0.3-frame-hook-self/main.npdm \
        --version-json ../acnh-agent/dist/version.json --out build/scratch/dev-payload
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import shutil
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
WORKSPACE = REPO_ROOT.parent.parent
AGENT = WORKSPACE / "src" / "acnh-agent"

DEFAULT_NSO = AGENT / "dist" / "acnh-agent.nso"
DEFAULT_NPDM = AGENT / "dist" / "acnh-3.0.3-frame-hook-self" / "main.npdm"
DEFAULT_VERSION_JSON = AGENT / "dist" / "version.json"
DEFAULT_OUT = REPO_ROOT / "build" / "scratch" / "dev-payload"

EXEFS = "atmosphere/contents/01006F8002326000/exefs"
CONTENT_ID = "E10617820DB06889E1638499478DA0DE"
BUILD_ID = "FF1D1C05670DB6021C85B624A710B963"
TITLE_VERSION = 2228224


def sha256_of(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nso", type=pathlib.Path, default=DEFAULT_NSO)
    parser.add_argument("--npdm", type=pathlib.Path, default=DEFAULT_NPDM)
    parser.add_argument("--version-json", type=pathlib.Path, default=DEFAULT_VERSION_JSON)
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    for path in (args.nso, args.npdm, args.version_json):
        if not path.is_file():
            print(f"error: missing input {path}", file=sys.stderr)
            return 1

    version = json.loads(args.version_json.read_text())
    nso_sha = sha256_of(args.nso)
    npdm_sha = sha256_of(args.npdm)
    version_sidecar = args.version_json.read_bytes()

    out_payload = args.out / "payload"
    out_payload.mkdir(parents=True, exist_ok=True)
    files = [
        ("subsdk9", args.nso, f"{EXEFS}/subsdk9", nso_sha, "game"),
        ("main.npdm", args.npdm, f"{EXEFS}/main.npdm", npdm_sha, "game"),
    ]
    # 侧车写进 payload 目录,清单里直接用它的哈希。
    sidecar = out_payload / "acnh-agent.version"
    sidecar.write_bytes(version_sidecar)
    files.append(("acnh-agent.version", sidecar, f"{EXEFS}/acnh-agent.version",
                  hashlib.sha256(version_sidecar).hexdigest(), "none"))
    for name, source, _target, _sha, _restart in files:
        if source != sidecar:
            shutil.copyfile(source, out_payload / name)

    manifest = {
        "schema": 1,
        "channel": "dev",
        "generated": "",
        "app": {"minVersion": "0.1.0"},
        "agent": {
            "version": version.get("agentVersion", "unknown"),
            "commit": version.get("commit", "unknown"),
            "dirty": bool(version.get("dirty", True)),
            "buildFlags": int(version.get("buildFlags", 0)),
        },
        "baseUrl": f"https://lextuo.com/acnh-chat-code/guide/agent/{version.get('agentVersion', 'dev')}/",
        "changelog": "dev payload generated by tools/make-dev-manifest.py",
        "games": [
            {
                "profile": "v3_0_3",
                "titleId": "01006F8002326000",
                "version": TITLE_VERSION,
                "displayVersion": "3.0.3",
                "contentId": CONTENT_ID,
                "buildId": BUILD_ID,
                "files": [
                    {"name": name, "source": name, "target": target, "size": size, "sha256": sha,
                     "restart": restart}
                    for (name, _src, target, sha, restart), size in zip(
                        files,
                        [args.nso.stat().st_size, args.npdm.stat().st_size, len(version_sidecar)],
                    )
                ],
            }
        ],
    }
    manifest_path = args.out / "dev-manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"agent {manifest['agent']['version']} commit={manifest['agent']['commit']} "
          f"dirty={manifest['agent']['dirty']} buildFlags={manifest['agent']['buildFlags']}")
    print(f"wrote {manifest_path}")
    for name, _source, target, sha, _restart in files:
        print(f"  {out_payload / name}  ->  {target}  sha256={sha[:16]}…")
    if manifest["agent"]["buildFlags"] != 2 or manifest["agent"]["dirty"]:
        print("note: 这是开发构建,发布门控会拒绝它;真机干跑请在 App 设置里打开"
              "\"允许开发清单\"。")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
